import { GoogleGenAI } from "@google/genai";

// Ensure the API key is available in the environment variables
// const apiKey = process.env.API_KEY;
// if (!apiKey) {
//     throw new Error("API_KEY environment variable not set");
// }
// const ai = new GoogleGenAI({ apiKey });

export async function generateEmail(prompt: string, type: 'follow-up' | 'outreach' | 'reminder'): Promise<string> {
    
    // MOCK IMPLEMENTATION - NO API CALL
    console.log(`Generating mock email for type: ${type} with prompt: "${prompt}"`);
    
    const mockEmail = `
Subject: Regarding Your Recent Inquiry

Hi Team,

This is a sample email generated by the AI Assistant. 

Type: ${type}
Prompt: ${prompt}

This demonstrates the frontend functionality without making a real API call. The actual content would be generated by the Gemini API in a production environment.

Best regards,

Nexora AI Assistant
    `;

    // Simulate network delay
    return new Promise(resolve => {
        setTimeout(() => {
            resolve(mockEmail.trim());
        }, 500);
    });

    /*
    // REAL API CALL (Commented out)
    const fullPrompt = `
        You are an expert sales assistant for a small business. Your tone is professional, friendly, and concise.
        Generate an email for the following request. Make sure to include a clear subject line and a professional closing.

        Email Type: ${type}
        Request: "${prompt}"
    `;

    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: fullPrompt,
        });
        
        return response.text;
    } catch (error) {
        console.error("Error generating email with Gemini API:", error);
        return "Sorry, I couldn't generate the email. Please check the console for more details.";
    }
    */
}